#!/data/data/com.termux/files/usr/bin/bash

# TERMUX-YTD 2.0
# BY KHAN SAAD
# GITHUB.COM/KHANSAAD1275

# SETTINGS THAT YOU CAN CHANGE-----


fpath='/data/data/com.termux/files/home/storage/shared/BB-SOCIAL-DOWNLOADER-TERMUX/%(title)s.%(ext)s'


# ----------

#check if reel

if [[ "$1" == *"short"* ]]; then
  yt-dlp -o $fpath $1 
  exit

else
	echo -e " "
fi



echo -e  "════════════════════════════════════════" 
echo -e  "   BB SOCIAL DOWNLOADER TERMUX  "
echo -e  ""
echo -e  "       ♚ Owner Info ♚     "
echo -e  " ♚ Owner : BIG BOSS (#bigboss/@bigboss) "  
echo -e  " ♚ Real Nmae : Eshan Diwayan Fdo (Chabhi)  "                                                                       
echo -e  " ♚ Age        : 19 "
echo -e  "  "
echo -e  "    Social Media Links and User Names  "
echo -e  " 🔰 Telegram Channel : @bb_alfa_team_channel "
echo -e  " 🔰 YouTube : https://youtube.com/@big_boss-sl"
echo -e  " 🔰 TikTok : https://www.tiktok.com/@bigboss_alfa_team_owner"
echo -e  " 🔰 Facebook : https://www.facebook.com/share/1D7SHd4uWV/"
echo -e  " 🔰 Discord : https://discord.gg/3bGx2aq6k"
echo -e  "  "
echo -e  "    ⚜️ Media Info ⚜️                                                          "
echo -e  " "
echo -e  " ♚ Url : $1 "
echo -e  " "
echo -e  "════════════════════════════════════════"
echo -e  "╠═▶ Please select the number and (A or E ) "
echo -e  "╠ "
echo -e  "╠═▶  [𝗦𝗲𝗹𝗲𝗰𝘁 Qulity and Formats]  "
echo -e  "╠ "
echo -e  "╠═▶ Audio Formats "
echo -e  "╠"
echo -e  "╠═▶ 1. m4a  Audio"
echo -e  "╠═▶ 2. mp3 Audio"
echo -e  "╠═▶ 3.  ogg Audio"
echo -e  "╠═▶ 4. mkv Audio"
echo -e  "╠═▶ 5. aac Audio"
echo -e  "╠ "
echo -e  "╠═▶ Video Formats "
echo -e  "╠ "
echo -e  "╠═▶ 6. 144p Video"
echo -e  "╠═▶ 7. 240p Video"
echo -e  "╠═▶ 8. 250p Video"
echo -e  "╠═▶ 9. 360p Video"
echo -e  "╠═▶10. 450p Video"
echo -e  "╠═▶ 11. 480p Video"
echo -e  "╠═▶ 12. 520p Video"
echo -e  "╠═▶ 13. 720p Video"
echo -e  "╠═▶ 14. 720p60p Video"
echo -e  "╠═▶ 15. 1080p Video"
echo -e  "╠═▶ 16. 1080p60p Video"
echo -e  "╠═▶ 17. 1440p Video"
echo -e  "╠═▶ 18. 2160l Video"
echo -e  "╠═▶ 19. 4320p Video"
echo -e  "╠═▶ 20. 8000p (test only) Video"
echo -e  "╠═▶ A. About"
echo -e  "╠═▶  E. Exsit"
echo -e  "════════════════════════════════════════"
    printf "╚═:➤ \e[0m "
read choice


case $choice in 
	1)
	yt-dlp -f 'bestaudio[ext=m4a]' -o $fpath $1
 ;;
 
 2)
	yt-dlp -f 'bestaudio[ext=mp3]' -o $fpath $1
 ;;
 
 3)
	yt-dlp -f 'bestaudio[ext=ogg]' -o $fpath $1
 ;;
 
 4)
	yt-dlp -f 'bestaudio[ext=mkv]' -o $fpath $1
 ;;
 
 5)
	yt-dlp -f 'bestaudio[ext=aac]' -o $fpath $1
 ;;
 
 
	6)
	yt-dlp -f "best[height<=144]" -o $fpath $1 
	;;

	7)
	yt-dlp -f "best[height<=240]" -o $fpath $1 
	;;
	
	8)
	yt-dlp -f "best[height<=250]" -o $fpath $1 
	;;
	
	9)
	yt-dlp -f "best[height<=360]" -o $fpath $1 
	;;
	
	10)
	yt-dlp -f "best[height<=450]" -o $fpath $1 
	;;
	
	11)
	yt-dlp -f 'best[height<=480]' -o $fpath $1 
	;;

	12)
	yt-dlp -f "best[height<=520]" -o $fpath $1 
	;;
	
	13)
	yt-dlp -f 'best[height<=720]' -o $fpath $1 
	;;

	14)
	yt-dlp -f "best[height<=720p60]" -o $fpath $1 
	;;
	
	15)
	yt-dlp -f 'best[height<=1080]' -o $fpath $1 
	;;

	16)
	yt-dlp -f "best[height<=1080p60]" -o $fpath $1 
	;;
	
	17)
	yt-dlp -f 'best[height<=1440]' -o $fpath $1 
	;;

	18)
	yt-dlp -f 'best[height<=2160]' -o $fpath $1 
	;;
	
	19)
	yt-dlp -f 'best[height<=4320]' -o $fpath $1 
	;;
	
	20)
	yt-dlp -f 'best[height<=8000]' -o $fpath $1 
	;;
	
	E)
	break
	;;
	
	A)
echo -e " ⭕ HOW  TO WORK THIS TOOL ⭕"
echo -e " "
echo -e " 🔰 Please fallow step by step 🔰"
echo -e " "
echo -e " open another social media app exsample : youtube  chooce do you want to download video"
echo -e " click share icon and find termux or same like app (TEL) Or any and automaticaly show "
echo -e " After select format or Qulity download"
echo -e " Enjoi my tool have a nice day"
echo -e " "
echo -e " ⚜️ Do you want to update this tool ⚜️"
echo -e " "
echo -e " cd MDBIGBOSS and bash up.sh use this tow command update"
echo -e " This tool Automaticaly "
	;;	

	*)
	yt-dlp -f 'best[height<=480]' -o $path $1 
esac
